CREATE DATABASE QLCF
USE QLCF
GO
drop database QLCF
-- Tạo table
CREATE TABLE ACCOUNT
(
	ID INT IDENTITY(1,1) NOT NULL,
	TK NVARCHAR(100) NOT NULL,
	MK NVARCHAR(100) NOT NULL,
)
CREATE TABLE MON
(
	MaM CHAR(4) NOT NULL,
	TenMon NVARCHAR(100),
	DonGia SMALLMONEY,
	MaLoai INT
)
CREATE TABLE PHANLOAI
(
	MaLoai INT IDENTITY(1,1) NOT NULL,
	TenLoai NVARCHAR(100)
)
CREATE TABLE HOADON 
(
	MaHD INT IDENTITY(1,1) NOT NULL,
	NgXuat DATE,
	TongGia MONEY,
)
CREATE TABLE CTHD
(
	MaHD INT NOT NULL,
	MaM CHAR(4) NOT NULL,
	SL INT
)
CREATE TABLE PHIEUCHI
(
	MaPC INT IDENTITY(1,1) NOT NULL,
	NgNhap DATE,
	TongGia MONEY
)
CREATE TABLE CTPC
(
	MaPC INT NOT NULL,
	MaNgL INT NOT NULL,
	SL INT
)
CREATE TABLE NGUYENLIEU
(
	MaNgL INT IDENTITY(1,1) NOT NULL,
	TenNgL NVARCHAR(100),
	DonGia SMALLMONEY,
	DonVi NVARCHAR(100)
)
--Thiết lập khóa chính

ALTER TABLE ACCOUNT 
ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY(ID)

ALTER TABLE MON
ADD CONSTRAINT PK_MON PRIMARY KEY(MaM)

ALTER TABLE PHANLOAI
ADD CONSTRAINT PK_PHANLOAI PRIMARY KEY (MaLoai)

ALTER TABLE HOADON
ADD CONSTRAINT PK_HOADON PRIMARY KEY (MaHD)

ALTER TABLE CTHD
ADD CONSTRAINT PK_CTHD PRIMARY KEY (MaHD,MaM)

ALTER TABLE NGUYENLIEU
ADD CONSTRAINT PK_NGUYENLIEU PRIMARY KEY(MaNgL)

ALTER TABLE PHIEUCHI
ADD CONSTRAINT PK_PHIEUCHI PRIMARY KEY (MaPC)

ALTER TABLE CTPC
ADD CONSTRAINT PK_CTPC PRIMARY KEY (MaPC,MaNgL)

--Thiết lập khóa ngoại

ALTER TABLE MON
ADD CONSTRAINT FK_MON_PHANLOAI FOREIGN KEY (MaLoai) REFERENCES PHANLOAI(MaLoai)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_MON FOREIGN KEY (MaM) REFERENCES MON(MaM)

ALTER TABLE CTPC
ADD CONSTRAINT FK_CTPC_PHIEUCHI FOREIGN KEY (MaPC) REFERENCES PHIEUCHI(MaPC)

ALTER TABLE CTPC
ADD CONSTRAINT FK_CTPC_NGUYENLIEU FOREIGN KEY (MaNgL) REFERENCES NGUYENLIEU(MaNgL) 


--INSERT


INSERT INTO ACCOUNT(TK,MK)
VALUES ('admin','123')


INSERT INTO PHANLOAI(TenLoai)
VALUES (N'CÀ PHÊ VIỆT NAM'),
		(N'CÀ PHÊ MÁY'),
		(N'ĐÁ XAY'),
		(N'TRÀ TRÁI CÂY'),
		(N'TRÀ SỮA MACCHIATO')


INSERT INTO MON(MaM,TenMon,DonGia,MaLoai)
VALUES (1001,N'Cà Phê Đen',20000, 1),
		(1002,N'Cà Phê Sữa',25000, 1),
		(1003,N'Bạc xỉu',29000, 1),

		(2001,N'Americano',39000, 2),
		(2002,N'Cappucino',39000, 2),
		(2003,N'Caramel Macchiato',39000, 2),
		(2004,N'Espresso',39000, 2),
		(2005,N'Latte',39000, 2),
		(2006,N'Mocha',39000, 2),

		(3001,N'Phúc Bồn Tử',32000, 3),
		(3002,N'Sữa Tươi Macchiato',32000, 3),
		(3003,N'Sữa tươi',32000, 3),
		(3004,N'Truyền thống',32000, 3),

		(4001,N'Trà Đào Cam Sả',30000, 4),
		(4002,N'Trà Hạt Sen',30000, 4),
		(4003,N'Trà phúc bồn tử',30000, 4),
		(4004,N'Trà vải',30000, 4),

		(5001,N'Trà đen Macchiato',35000, 5),
		(5002,N'Trà lài Macchiato',35000, 5),
		(5003,N'Matcha Macchiato',35000, 5),
		(5004,N'Trà sữa trân châu',35000, 5),
		(5005,N'Trà xoài Macchiato',35000, 5)

SET IDENTITY_INSERT dbo.HOADON ON
CREATE PROC USP_InsertHOADON
@Tonggia MONEY
AS
BEGIN
	INSERT dbo.HOADON 
	        ( NgXuat ,
	          TongGia 	    
	        )
	VALUES  ( GETDATE() ,
	          @TongGia
	        )
END
GO

CREATE PROC USP_InsertCTHD
@MaHD INT, @MaM Char(4), @SL INT
AS
BEGIN
	INSERT dbo.CTHD
    (MaHD, MaM, SL )
	VALUES  ( @MaHD,  @MaM,  @SL )
END

SET IDENTITY_INSERT dbo.PHIEUCHI ON
CREATE PROC USP_InsertPHIEUCHI
@Tonggia MONEY
AS
BEGIN
	INSERT dbo.PHIEUCHI 
	        ( NgNhap ,
	          TongGia 	    
	        )
	VALUES  ( GETDATE() ,
	          @TongGia
	        )
END
GO

CREATE PROC USP_InsertCTPC
@MaPC INT, @MaNgL INT, @SL INT
AS
BEGIN
	INSERT dbo.CTPC
    (MaPC, MaNgL, SL )
	VALUES  ( @MaPC,  @MaNgL,  @SL )
END


CREATE PROC USP_InsertNGUYENLIEU
@MaNgL INT, @TenNgL NVARCHAR(100),@DonGia SMALLMONEY,@DonVi NVARCHAR(100)
AS
BEGIN
	INSERT dbo.NGUYENLIEU
	(MaNgL,TenNgL ,DonGia ,DonVi)
	VALUES ( @MaNgL, @TenNgL, @DonGia, @DonVi )
END